### ISSUE TITLE
cudaErrorNoKernelImageForDevice

### ISSUE THREAD

**Issue by rtlr** [quim0/eWFA-GPU#1]
Hi there!

Building this on Ubuntu 20.04 using standard sm and compute and running wfe.aligner gives error for no kernel for the device.
Running on a 4090 GPU.
Any ideas on what may be causing this?
Thank you

**Comment by quim0** [comment]
Hello,

The Makefile is configured to generate code for GPUs with compute capability 7.0, the GPU you are using has the compute capability 9.0. To solve the problem, you need to change the first line of the Makefile:

```
SM=90
COMPUTE=$(SM)
NVCC=nvcc
CC=gcc
... rest of the file
```

No how `SM` value is changed from 70 to 90.

Let me know if this solves the issue. If you find any other problem I'll be happy to help.

**Comment by rtlr** [comment]
So there may have been some issues with my setup causing it to not build properly. All sorted now, thanks!
